name: skybase

services:
    db:
        image: mysql:9
        container_name: skybase_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: skybase
            MYSQL_USER: skybase
            MYSQL_PASSWORD: skybase
        ports:
            - "3310:3306"
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysql -uskybase -pskybase -e'USE skybase'"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 30s
            start_interval: 5s
    api:
        image: skybase:1.0.1
        container_name: skybase_api
        ports:
            - "8888:8081"
        depends_on:
            db:
                condition: service_healthy
volumes:
    dbdata:
